# Site settings
title: Poise
email: joshuavaage@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A multi-author Jekyll theme that is lightweight, simple to use and read, and is fantastic.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: whaleen
github_username:  whaleen

# Build settings
markdown: kramdown

sass:
  style: compressed

authors:
  joshuavaage:
    handle: joshuavaage
    name: Joshua Vaage
    job_title: Front End Developer
    bio: Spent the 80's supervising the production of action figures on Wall Street. Developed several new methods for promoting Roombas with no outside help.
    thumbImg: images/authors/jvaage.jpg
  sarasmith:
    handle: sarasmith
    name: Sara Smith
    job_title: Co-founder and Product Manager
    bio: Earned praised for my work analyzing squirt guns in Los Angeles, CA. Spent college summers merchandising glucose on the black market. Lead a team buying and selling shaving cream in Atlantic City, NJ.
    thumbImg: images/authors/sara_smith.png
